### ISSUE TITLE
Wrap notes outside range using modulo not min/max

### ISSUE THREAD

**Issue by oO** [albertfc/antz#1]
The note range of the Ants! is 36-96 or C3 to C8. But right now, notes outside the range are simply clamped to the min/max value of the range when they should be folded to the same note in the playable range.

Playing D8 ( Note #98 ) should be mapped to D7 ( Note #86 ) and not clamped to C8 (96)

Pseudocode should be something like this:

    if (note > max) {
      note = (max - 12) + (note mod 12)
    }
    else if (note < min) {
      note = min + (note mod 12)
    }

This would remove the problem of hearing a C when you are playing a D

**Comment by albertfc** [comment]
Thanks @oO for pointing out this issue. We have decided to address it by just omitting "playing" notes outside the supported range as many other converters do. However the led which indicates MIDI messages reception still blinks so the user is aware it works.

Fixed in commit 99ba06e050b6face620d2369fb0f70c60a71d7c2

**Comment by oO** [comment]
Sounds good. muting is musically better than clamping. thanks.
